baseURL = "https://rajendrasinh-ai.github.io/"
languageCode = "en-us"
title = "Rajendrasinh Parmar"
canonifyurls = true
theme = "hugo-nuo"

[params]
  author = "Rajendrasinh Parmar"
  avatar = "/img/avatar.jpg"
  seotitle = "Rajendrasinh Parmar Blog"
  subtitle = "~ The Game of Karma ~"
  description = "Blog website from Rajendrasinh Parmar"
  paginate = 10